FROM sago007/docker_blockattack

RUN apt-get update && apt-get install -y zip gettext mxe-i686-w64-mingw32.static-sdl2-gfx mxe-i686-w64-mingw32.static-libxml2 mxe-i686-w64-mingw32.static-box2d

RUN mkdir -p /staging/saland

COPY . /staging/saland

RUN cd /staging/saland && \
i686-w64-mingw32.static-cmake . && \
make
